title: テルミン・ラボ
description: テルミンに関する研究・DIY・資料アーカイブ
url: "https://nobury-lab.github.io"
baseurl: "/theremin-lab"

theme: just-the-docs

lang: ja

nav_fold: false

aux_links:
  "GitHub":
    - "https://github.com/nobury-lab/theremin-lab"

kramdown:
  footnote_backlink: "▲"

callouts:
  note:
    title: メモ
    color: blue
  warning:
    title: 注意
    color: red
  important:
    title: 重要
    color: yellow
  tip:
    title: ヒント
    color: green
  info:
    title: 情報
    color: purple
  model:
    color: grey-dk

favicon_ico: "/assets/images/favicon.ico"
footer_content: "© 2026- theremin-lab / norbury"