title: テルミン・ラボ
description: テルミンに関する研究・DIY・資料アーカイブ
url: "https://nobury-lab.github.io"
baseurl: "/theremin-lab"

theme: just-the-docs

lang: ja

aux_links:
  "GitHub":
    - "https://github.com/nobury-lab/theremin-lab"

callouts:
  note:
    title: メモ
  warning:
    title: 注意
  important:
    title: 重要